### ISSUE TITLE
Add better control for legend labels

### ISSUE THREAD

**Issue by Sedzrokojo** [asjadnaqvi/stata-spider#12]
Is it possible to add export as option to export to any format like pdf, jpeg, png etc

**Comment by asjadnaqvi** [comment]
Once you generate the graph, you can export it using the builtin Stata option: `graph export xxxx.yyy, replace` where `.yyy` is any format supported by Stata

**Comment by Sedzrokojo** [comment]
Thanks for the feedback Asjad. Please is there any way to edit the legend  and probably control the attribute labels in the spider graph
Thank you.
Sedzro
