### ISSUE TITLE
option by() not allowed -- add checks to make sure `by()` has at least three categories.

### ISSUE THREAD

**Issue by CaroHinca** [asjadnaqvi/stata-spider#15]
https://www.statalist.org/forums/forum/general-stata-discussion/general/1752516-spider-stata-module-for-spider-plots-radar-plot

Dear  Asjad Naqvi, 

Currently I am trying to perform a Spider plot with the package spider, using Stata 18.

I was trying to follow up the tutorial that Asjad Naqvi kindly provide in GitHub:

GitHub - asjadnaqvi/stata-spider: spider: A Stata package for spider plots.

But unfortunately, the by() option is not allowed when I try to perform the code

Code:
spider Domain_score , over ( Domain_name ) by ( EQIndex_detoriation)
option by() not allowed
r(198);

Code:
* Example generated by -dataex-. For more info, type help dataex
clear
input float subject_id byte Domain_score str1 Domain_moment_BorF byte EQIndex_detoriation str19 Domain_name
6184 2 "b" 1 "Mobility"      
6184 1 "b" 1 "Selfcare"      
6184 2 "b" 1 "DailyActivities"
6184 1 "b" 1 "PainDiscomfort"
6184 1 "b" 1 "FearDepressed"  
6184 3 "f" 1 "Mobility"      
6184 1 "f" 1 "Selfcare"      
6184 4 "f" 1 "DailyActivities"
6184 3 "f" 1 "PainDiscomfort"
6184 2 "f" 1 "FearDepressed"  
5926 1 "b" 1 "Mobility"      
5926 1 "b" 1 "Selfcare"      
5926 1 "b" 1 "DailyActivities"
5926 1 "b" 1 "PainDiscomfort"
5926 1 "b" 1 "FearDepressed"  
5926 1 "f" 1 "Mobility"      
5926 2 "f" 1 "Selfcare"      
5926 2 "f" 1 "DailyActivities"
5926 2 "f" 1 "PainDiscomfort"
5926 1 "f" 1 "FearDepressed"  
5800 1 "b" 1 "Mobility"      
5800 1 "b" 1 "Selfcare"      
5800 2 "b" 1 "DailyActivities"
5800 1 "b" 1 "PainDiscomfort"
5800 2 "b" 1 "FearDepressed"  
5800 2 "f" 1 "Mobility"      
5800 2 "f" 1 "Selfcare"      
5800 3 "f" 1 "DailyActivities"
5800 1 "f" 1 "PainDiscomfort"
5800 1 "f" 1 "FearDepressed"  
5731 1 "b" 1 "Mobility"      
5731 1 "b" 1 "Selfcare"      
5731 1 "b" 1 "DailyActivities"
5731 2 "b" 1 "PainDiscomfort"
5731 2 "b" 1 "FearDepressed"  
5731 1 "f" 1 "Mobility"      
5731 3 "f" 1 "Selfcare"      
5731 4 "f" 1 "DailyActivities"
5731 3 "f" 1 "PainDiscomfort"
5731 4 "f" 1 "FearDepressed"  
5690 5 "b" 1 "Mobility"      
5690 5 "b" 1 "Selfcare"      
5690 1 "b" 1 "DailyActivities"
5690 4 "b" 1 "PainDiscomfort"
5690 2 "b" 1 "FearDepressed"  
5690 5 "f" 1 "Mobility"      
5690 5 "f" 1 "Selfcare"      
5690 3 "f" 1 "DailyActivities"
5690 4 "f" 1 "PainDiscomfort"
5690 1 "f" 1 "FearDepressed"  
5644 1 "b" 1 "Mobility"      
5644 1 "b" 1 "Selfcare"      
5644 1 "b" 1 "DailyActivities"
5644 3 "b" 1 "PainDiscomfort"
5644 2 "b" 1 "FearDepressed"  
5644 3 "f" 1 "Mobility"      
5644 1 "f" 1 "Selfcare"      
5644 3 "f" 1 "DailyActivities"
5644 1 "f" 1 "PainDiscomfort"
5644 2 "f" 1 "FearDepressed"  
5474 1 "b" 1 "Mobility"      
5474 1 "b" 1 "Selfcare"      
5474 1 "b" 1 "DailyActivities"
5474 3 "b" 1 "PainDiscomfort"
5474 1 "b" 1 "FearDepressed"  
5474 3 "f" 1 "Mobility"      
5474 1 "f" 1 "Selfcare"      
5474 3 "f" 1 "DailyActivities"
5474 3 "f" 1 "PainDiscomfort"
5474 2 "f" 1 "FearDepressed"  
5466 2 "b" 1 "Mobility"      
5466 2 "b" 1 "Selfcare"      
5466 1 "b" 1 "DailyActivities"
5466 1 "b" 1 "PainDiscomfort"
5466 1 "b" 1 "FearDepressed"  
5466 1 "f" 1 "Mobility"      
5466 1 "f" 1 "Selfcare"      
5466 2 "f" 1 "DailyActivities"
5466 2 "f" 1 "PainDiscomfort"
5466 1 "f" 1 "FearDepressed"  
5394 1 "b" 1 "Mobility"      
5394 1 "b" 1 "Selfcare"      
5394 1 "b" 1 "DailyActivities"
5394 1 "b" 1 "PainDiscomfort"
5394 1 "b" 1 "FearDepressed"  
5394 5 "f" 1 "Mobility"      
5394 1 "f" 1 "Selfcare"      
5394 5 "f" 1 "DailyActivities"
5394 1 "f" 1 "PainDiscomfort"
5394 1 "f" 1 "FearDepressed"  
5300 1 "b" 1 "Mobility"      
5300 1 "b" 1 "Selfcare"      
5300 1 "b" 1 "DailyActivities"
5300 1 "b" 1 "PainDiscomfort"
5300 1 "b" 1 "FearDepressed"  
5300 2 "f" 1 "Mobility"      
5300 1 "f" 1 "Selfcare"      
5300 2 "f" 1 "DailyActivities"
5300 2 "f" 1 "PainDiscomfort"
5300 1 "f" 1 "FearDepressed"  
end

I also have a second issue, and not sure how to solve it:
The labels in the radar are quite weird (1-2-2-2-2 instead of 0-1-2-3-4-5), and I can't edit them in the edition window

Thanks in advance for your help!

**Comment by asjadnaqvi** [comment]
Dear @CaroHinca,

`tab EQIndex_detoriation` shows that there is only category so this is not a valid `by()` or `over()` option. I should add a check for this but the `by()` should have at least 3 categories to at least make a triangle.

But the following two commands work well and the label 1-2-2-2-2 is a format issue that can be easily fixed.

```
spider Domain_score, by(Domain_name) raformat(%5.2f)
```
![spider1](https://github.com/asjadnaqvi/stata-spider/assets/38498046/2102753d-bd13-4cb0-86b4-b45427054b1a)

```
spider Domain_score, by(Domain_name) over(Domain_moment_BorF) raformat(%5.2f)
```

![spider2](https://github.com/asjadnaqvi/stata-spider/assets/38498046/7a0610e6-5203-4099-aab9-ab007403ce0d)

Can you double check your commands please and let me know.

**Comment by CaroHinca** [comment]
Amazing! 
Thanks a lot!
