### ISSUE TITLE
WHY it shows "command shapes is unrecognized"

### ISSUE THREAD

**Issue by RUCYXK** [asjadnaqvi/stata-spider#18]
When I finished the installation and run the spider, the "command shapes is unrecognized" is found in screen, how to deal with it?

**Comment by asjadnaqvi** [comment]
install this directly from GitHub:  
```
net install graphfunctions, from("https://raw.githubusercontent.com/asjadnaqvi/stata-graphfunctions/main/installation/") replace
```

The SSC version doesn't currently have the `shapes` program.

**Comment by RUCYXK** [comment]
Thanks! It makes sense now.



Best regards,

Xiaokun


--

Bryce, Yu Xiaokun

Department of Economics, FSS
University of Macau
Tel.: 853-63531779
Email: ***@***.***



重要提示：此]件的热莺腿魏胃郊际潜Ｃ艿摹Ｎ唇l件人嫱猓澜c任何第三方分享此消息的任何部分。如果您`收到此消息，回复此消息Kh除，xx。



IMPORTANT: The contents of this email and any attachments are confidential. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, thanks.



* Please consider the environment before printing this email.

________________________________
发件人: Asjad Naqvi ***@***.***>
发送时间: 2024年10月15日 13:21
收件人: asjadnaqvi/stata-spider ***@***.***>
抄送: Bryce YU ***@***.***>; Author ***@***.***>
主题: Re: [asjadnaqvi/stata-spider] WHY it shows "command shapes is unrecognized" (Issue #18)


install this directly from GitHub:

net install graphfunctions, from("https://raw.githubusercontent.com/asjadnaqvi/stata-graphfunctions/main/installation/") replace


The SSC version doesn't currently have the shapes program.

―

**Comment by asjadnaqvi** [comment]
Thank you for pointing it out! I have updated the readme with better instructions on how deal with this.
